dist: xenial
sudo: required

language: c ruby
rvm:
  - "2.6"

install:
  - sudo apt-get install gcc
  - gem install rake
  - gem install ceedling
  - pip install --user gcovr

script:
  - cd test/unit-test/test_logger/
  - ceedling test:all
  - ceedling gcov:all utils:gcov

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"